/*=============================================================================
  DQ_Framework_Config.sql
  Data Quality Framework - Step 4: Framework Schema, Tables & Config Loading
=============================================================================*/

-- =============================================
-- 1. Create Framework Schema
-- =============================================
CREATE SCHEMA IF NOT EXISTS BANKING_DQ_DB.DQ_MONITORING;

-- =============================================
-- 2. Framework Tables
-- =============================================

-- Run Control: tracks each rule execution per run
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RUN_CONTROL (
    RUN_ID VARCHAR(50) NOT NULL,
    RULE_ID VARCHAR(50) NOT NULL,
    RUN_START_TIME TIMESTAMP_NTZ(9),
    RUN_END_TIME TIMESTAMP_NTZ(9),
    RULE_EXEC_RESULT VARCHAR(50),
    RULE_OUTPUT_VALUE VARCHAR(1000),
    RUN_STATUS VARCHAR(50),
    TRIGGERED_BY VARCHAR(100),
    ERROR_MESSAGE VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Rule Config: master table of all DQ rules
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (
    RULE_ID VARCHAR(50) NOT NULL,
    RULE_NAME VARCHAR(200) NOT NULL,
    RULE_TYPE VARCHAR(50) NOT NULL,
    FREQUENCY VARCHAR(50) DEFAULT 'TRIGGER_ON_CHANGES',
    CRITICALITY VARCHAR(10) NOT NULL,
    DB_NAME VARCHAR(200) NOT NULL,
    TABLE_NM VARCHAR(200) NOT NULL,
    COLUMN_NM VARCHAR(500),
    RULE_DESCRIPTION VARCHAR(1000),
    RULE_SQL VARCHAR(4000),
    THRESHOLD_VALUE NUMBER(18,4) DEFAULT 0,
    RULE_DIMENSION VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Rule Results: detailed pass/fail results per rule per run
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_RESULTS (
    RESULT_ID VARCHAR(50) NOT NULL,
    RUN_ID VARCHAR(50) NOT NULL,
    RULE_ID VARCHAR(50) NOT NULL,
    DB_NAME VARCHAR(200),
    TABLE_NAME VARCHAR(200),
    COLUMN_NAME VARCHAR(500),
    RULE_NAME VARCHAR(200),
    RULE_TYPE VARCHAR(50),
    EXPECTED_VALUE VARCHAR(200),
    ACTUAL_VALUE VARCHAR(200),
    FAILED_RECORD_COUNT NUMBER(18,0),
    TOTAL_RECORD_COUNT NUMBER(18,0),
    PASS_PERCENTAGE NUMBER(7,2),
    RESULT_STATUS VARCHAR(20),
    SEVERITY VARCHAR(10),
    ERROR_SAMPLE_QUERY VARCHAR(4000),
    EXECUTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Error Records: captures sample error records for investigation
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ERROR_RECORDS (
    ERROR_ID VARCHAR(50) NOT NULL,
    RUN_ID VARCHAR(50) NOT NULL,
    RULE_ID VARCHAR(50) NOT NULL,
    DB_NAME VARCHAR(200),
    TABLE_NAME VARCHAR(200),
    ERROR_RECORD_VARIANT VARIANT,
    ERROR_REASON VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Anomaly Results: tracks anomalies detected in DQ metrics
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ANOMALY_RESULTS (
    ANOMALY_ID VARCHAR(50) NOT NULL,
    RUN_ID VARCHAR(50) NOT NULL,
    DATABASE_NAME VARCHAR(200),
    SCHEMA_NAME VARCHAR(200),
    TABLE_NAME VARCHAR(200),
    METRIC_NAME VARCHAR(200),
    CURRENT_VALUE NUMBER(18,4),
    PREVIOUS_VALUE NUMBER(18,4),
    BASELINE_AVG NUMBER(18,4),
    BASELINE_STDDEV NUMBER(18,4),
    ANOMALY_STATUS VARCHAR(50),
    ANOMALY_REASON VARCHAR(1000),
    DETECTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- 3. Load Rule Configuration (42 rules)
-- =============================================

-- LOAN_APPLICATIONS rules (LA01-LA10)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'LA01','Loan App Row Count Monitor','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS',NULL,'Monitor row count stability','ROW_COUNT',0,PARSE_JSON('["volume"]'),TRUE
UNION ALL SELECT 'LA02','Application ID Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_ID','APPLICATION_ID must not be NULL','NULL_COUNT(APPLICATION_ID)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA03','Requested Amount Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','REQUESTED_AMOUNT','REQUESTED_AMOUNT must not be NULL','NULL_COUNT(REQUESTED_AMOUNT)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA04','Credit Score Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CREDIT_SCORE','CREDIT_SCORE must not be NULL','NULL_COUNT(CREDIT_SCORE)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA05','Application ID Uniqueness','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_ID','APPLICATION_ID must be unique','DUPLICATE_COUNT(APPLICATION_ID)',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'LA06','Requested Amount Positive','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','REQUESTED_AMOUNT','REQUESTED_AMOUNT must be > 0','ZERO_OR_NEGATIVE_COUNT(REQUESTED_AMOUNT)',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'LA07','Credit Score Range Check','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CREDIT_SCORE','CREDIT_SCORE must be between 300 and 850','CREDIT_SCORE_OUT_OF_RANGE_COUNT(CREDIT_SCORE)',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'LA08','Approved <= Requested Amount','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','REQUESTED_AMOUNT,APPROVED_AMOUNT','APPROVED_AMOUNT must be <= REQUESTED_AMOUNT','APPROVED_EXCEEDS_REQUESTED_COUNT(REQUESTED_AMOUNT,APPROVED_AMOUNT)',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'LA09','Loan Type Accepted Values','CUSTOM_DMF','MEDIUM','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','LOAN_TYPE','LOAN_TYPE in HOME,CAR,PERSONAL,EDUCATION,BUSINESS','INVALID_LOAN_TYPE_COUNT(LOAN_TYPE)',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'LA10','Application Status Accepted Values','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_STATUS','APPLICATION_STATUS in APPROVED,PENDING,REJECTED','INVALID_APP_STATUS_COUNT(APPLICATION_STATUS)',0,PARSE_JSON('["consistency"]'),TRUE;

-- CUSTOMERS rules (CU01-CU10)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'CU01','Customer Row Count Monitor','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS',NULL,'Monitor row count stability','ROW_COUNT',0,PARSE_JSON('["volume"]'),TRUE
UNION ALL SELECT 'CU02','Customer ID Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','CUSTOMER_ID','CUSTOMER_ID must not be NULL','NULL_COUNT(CUSTOMER_ID)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU03','Email Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','EMAIL must not be NULL','NULL_COUNT(EMAIL)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU04','Phone Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','PHONE','PHONE must not be NULL','NULL_COUNT(PHONE)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU05','Customer ID Uniqueness','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','CUSTOMER_ID','CUSTOMER_ID must be unique','DUPLICATE_COUNT(CUSTOMER_ID)',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'CU06','Email Uniqueness','SYSTEM_DMF','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','EMAIL should be unique','DUPLICATE_COUNT(EMAIL)',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'CU07','Email Format Validation','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','EMAIL must match valid email pattern','INVALID_EMAIL_COUNT(EMAIL)',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU08','Phone Format Validation','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','PHONE','PHONE must be exactly 10 digits','INVALID_PHONE_COUNT(PHONE)',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU09','DOB Not in Future','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','DATE_OF_BIRTH','DOB must not be future or before 1900','UNREASONABLE_DOB_COUNT(DATE_OF_BIRTH)',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'CU10','KYC Status Accepted Values','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','KYC_STATUS','KYC_STATUS in VERIFIED,PENDING,REJECTED','INVALID_KYC_STATUS_COUNT(KYC_STATUS)',0,PARSE_JSON('["consistency"]'),TRUE;

-- ACCOUNTS rules (AC01-AC09)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'AC01','Account Row Count Monitor','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS',NULL,'Monitor row count stability','ROW_COUNT',0,PARSE_JSON('["volume"]'),TRUE
UNION ALL SELECT 'AC02','Account ID Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_ID','ACCOUNT_ID must not be NULL','NULL_COUNT(ACCOUNT_ID)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC03','Customer ID Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','CUSTOMER_ID','CUSTOMER_ID must not be NULL','NULL_COUNT(CUSTOMER_ID)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC04','Balance Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','BALANCE','BALANCE must not be NULL','NULL_COUNT(BALANCE)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC05','Account ID Uniqueness','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_ID','ACCOUNT_ID must be unique','DUPLICATE_COUNT(ACCOUNT_ID)',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'AC06','Balance Non-Negative','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','BALANCE','BALANCE should be >= 0','NEGATIVE_VALUE_COUNT(BALANCE)',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'AC07','Account Type Accepted Values','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_TYPE','ACCOUNT_TYPE in SAVINGS,CURRENT,LOAN','INVALID_ACCOUNT_TYPE_COUNT(ACCOUNT_TYPE)',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'AC08','Account Status Accepted Values','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_STATUS','ACCOUNT_STATUS in ACTIVE,DORMANT,CLOSED','INVALID_ACCOUNT_STATUS_COUNT(ACCOUNT_STATUS)',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'AC09','Currency Consistency','CUSTOM_DMF','MEDIUM','BANKING_DQ_DB.RAW','ACCOUNTS','CURRENCY','CURRENCY should be INR','NON_INR_CURRENCY_COUNT(CURRENCY)',0,PARSE_JSON('["consistency"]'),TRUE;

-- TRANSACTIONS rules (TX01-TX08)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'TX01','Transaction Row Count Monitor','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS',NULL,'Monitor row count stability','ROW_COUNT',0,PARSE_JSON('["volume"]'),TRUE
UNION ALL SELECT 'TX02','Transaction ID Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_ID','TRANSACTION_ID must not be NULL','NULL_COUNT(TRANSACTION_ID)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX03','Amount Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','AMOUNT','AMOUNT must not be NULL','NULL_COUNT(AMOUNT)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX04','Account ID Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','ACCOUNT_ID','ACCOUNT_ID must not be NULL','NULL_COUNT(ACCOUNT_ID)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX05','Transaction ID Uniqueness','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_ID','TRANSACTION_ID must be unique','DUPLICATE_COUNT(TRANSACTION_ID)',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'TX06','Amount Non-Negative','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','AMOUNT','AMOUNT must be >= 0','NEGATIVE_VALUE_COUNT(AMOUNT)',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'TX07','Transaction Type Accepted Values','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_TYPE','TRANSACTION_TYPE in DEBIT,CREDIT','INVALID_TXN_TYPE_COUNT(TRANSACTION_TYPE)',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'TX08','Transaction Status Accepted Values','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_STATUS','TRANSACTION_STATUS in SUCCESS,FAILED,PENDING','INVALID_TXN_STATUS_COUNT(TRANSACTION_STATUS)',0,PARSE_JSON('["consistency"]'),TRUE;

-- BRANCHES rules (BR01-BR05)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG
(RULE_ID, RULE_NAME, RULE_TYPE, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'BR01','Branch Row Count Monitor','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','BRANCHES',NULL,'Monitor row count stability','ROW_COUNT',0,PARSE_JSON('["volume"]'),TRUE
UNION ALL SELECT 'BR02','Branch ID Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_ID','BRANCH_ID must not be NULL','NULL_COUNT(BRANCH_ID)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR03','Branch Name Null Check','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_NAME','BRANCH_NAME must not be NULL','NULL_COUNT(BRANCH_NAME)',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR04','Branch ID Uniqueness','SYSTEM_DMF','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_ID','BRANCH_ID must be unique','DUPLICATE_COUNT(BRANCH_ID)',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'BR05','IFSC Code Format Validation','CUSTOM_DMF','HIGH','BANKING_DQ_DB.RAW','BRANCHES','IFSC_CODE','IFSC must match ^[A-Z]{4}[0-9]{7}$','INVALID_IFSC_COUNT(IFSC_CODE)',0,PARSE_JSON('["validity"]'),TRUE;
