/*=============================================================================
  DQ_Rules.sql
  Data Quality Framework - Step 3: DMF Creation & Attachment
  All system/custom DMFs created and attached to BANKING_DQ_DB.RAW tables
=============================================================================*/

-- =============================================
-- 1. Create Custom DMFs in DQ_MONITORING Schema
-- =============================================

-- 1.1 Validity: Email format
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_EMAIL_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND NOT ARG_C1 RLIKE '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
$$;

-- 1.2 Validity: Phone format (10 digits)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_PHONE_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND NOT ARG_C1 RLIKE '^[0-9]{10}$'
$$;

-- 1.3 Validity: IFSC code format
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_IFSC_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND NOT ARG_C1 RLIKE '^[A-Z]{4}[0-9]{7}$'
$$;

-- 1.4 Accuracy: Negative value check
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.NEGATIVE_VALUE_COUNT(
  ARG_T TABLE(ARG_C1 NUMBER(18,2))
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T WHERE ARG_C1 < 0
$$;

-- 1.5 Accuracy: Zero or negative check
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.ZERO_OR_NEGATIVE_COUNT(
  ARG_T TABLE(ARG_C1 NUMBER(18,2))
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T WHERE ARG_C1 <= 0
$$;

-- 1.6 Accuracy: Unreasonable DOB
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.UNREASONABLE_DOB_COUNT(
  ARG_T TABLE(ARG_C1 DATE)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND (YEAR(ARG_C1) > 2025 OR YEAR(ARG_C1) < 1900)
$$;

-- 1.7 Accuracy: Approved exceeds requested (cross-column)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.APPROVED_EXCEEDS_REQUESTED_COUNT(
  ARG_T TABLE(ARG_C1 NUMBER(18,2), ARG_C2 NUMBER(18,2))
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T WHERE ARG_C2 IS NOT NULL AND ARG_C2 > ARG_C1
$$;

-- 1.8 Validity: Credit score range
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.CREDIT_SCORE_OUT_OF_RANGE_COUNT(
  ARG_T TABLE(ARG_C1 NUMBER(5,0))
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL AND (ARG_C1 < 300 OR ARG_C1 > 850)
$$;

-- 1.9 Consistency: Account type
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_ACCOUNT_TYPE_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND ARG_C1 NOT IN ('SAVINGS','CURRENT','LOAN')
$$;

-- 1.10 Consistency: Account status
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_ACCOUNT_STATUS_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND ARG_C1 NOT IN ('ACTIVE','DORMANT','CLOSED')
$$;

-- 1.11 Consistency: Currency
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.NON_INR_CURRENCY_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL AND ARG_C1 != 'INR'
$$;

-- 1.12 Consistency: KYC status
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_KYC_STATUS_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND ARG_C1 NOT IN ('VERIFIED','PENDING','REJECTED')
$$;

-- 1.13 Consistency: Transaction type
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_TXN_TYPE_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND ARG_C1 NOT IN ('DEBIT','CREDIT')
$$;

-- 1.14 Consistency: Transaction status
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_TXN_STATUS_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND ARG_C1 NOT IN ('SUCCESS','FAILED','PENDING')
$$;

-- 1.15 Consistency: Loan type
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_LOAN_TYPE_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND ARG_C1 NOT IN ('HOME','CAR','PERSONAL','EDUCATION','BUSINESS')
$$;

-- 1.16 Consistency: Application status
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_APP_STATUS_COUNT(
  ARG_T TABLE(ARG_C1 VARCHAR)
)
RETURNS NUMBER AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE ARG_C1 IS NOT NULL
    AND ARG_C1 NOT IN ('APPROVED','PENDING','REJECTED')
$$;

-- =============================================
-- 2. Set DATA_METRIC_SCHEDULE on All Tables
-- =============================================
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS         SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS          SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS      SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES          SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- =============================================
-- 3. Attach System DMFs to Tables
-- =============================================

-- === LOAN_APPLICATIONS ===
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (APPLICATION_ID);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (REQUESTED_AMOUNT);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CREDIT_SCORE);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (APPLICATION_ID);

-- === CUSTOMERS ===
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (EMAIL);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PHONE);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (EMAIL);

-- === ACCOUNTS ===
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BALANCE);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ACCOUNT_ID);

-- === TRANSACTIONS ===
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_ID);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (AMOUNT);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TRANSACTION_ID);

-- === BRANCHES ===
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_ID);
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_NAME);
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (BRANCH_ID);

-- =============================================
-- 4. Attach Custom DMFs to Tables
-- =============================================

-- === LOAN_APPLICATIONS ===
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.ZERO_OR_NEGATIVE_COUNT ON (REQUESTED_AMOUNT);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.CREDIT_SCORE_OUT_OF_RANGE_COUNT ON (CREDIT_SCORE);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.APPROVED_EXCEEDS_REQUESTED_COUNT ON (REQUESTED_AMOUNT, APPROVED_AMOUNT);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_LOAN_TYPE_COUNT ON (LOAN_TYPE);
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_APP_STATUS_COUNT ON (APPLICATION_STATUS);

-- === CUSTOMERS ===
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_EMAIL_COUNT ON (EMAIL);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_PHONE_COUNT ON (PHONE);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.UNREASONABLE_DOB_COUNT ON (DATE_OF_BIRTH);
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_KYC_STATUS_COUNT ON (KYC_STATUS);

-- === ACCOUNTS ===
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.NEGATIVE_VALUE_COUNT ON (BALANCE);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_ACCOUNT_TYPE_COUNT ON (ACCOUNT_TYPE);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_ACCOUNT_STATUS_COUNT ON (ACCOUNT_STATUS);
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.NON_INR_CURRENCY_COUNT ON (CURRENCY);

-- === TRANSACTIONS ===
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.NEGATIVE_VALUE_COUNT ON (AMOUNT);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_TXN_TYPE_COUNT ON (TRANSACTION_TYPE);
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_TXN_STATUS_COUNT ON (TRANSACTION_STATUS);

-- === BRANCHES ===
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES ADD DATA METRIC FUNCTION BANKING_DQ_DB.DQ_MONITORING.INVALID_IFSC_COUNT ON (IFSC_CODE);

-- =============================================
-- 5. Verify All Attachments (42 DMFs across 5 tables)
-- =============================================
SELECT REF_ENTITY_NAME AS TABLE_NAME, METRIC_NAME, METRIC_DATABASE_NAME, METRIC_SCHEMA_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.BRANCHES', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, METRIC_DATABASE_NAME, METRIC_SCHEMA_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.CUSTOMERS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, METRIC_DATABASE_NAME, METRIC_SCHEMA_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.ACCOUNTS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, METRIC_DATABASE_NAME, METRIC_SCHEMA_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.TRANSACTIONS', REF_ENTITY_DOMAIN => 'table'))
UNION ALL
SELECT REF_ENTITY_NAME, METRIC_NAME, METRIC_DATABASE_NAME, METRIC_SCHEMA_NAME, SCHEDULE_STATUS
FROM TABLE(BANKING_DQ_DB.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
  REF_ENTITY_NAME => 'BANKING_DQ_DB.RAW.LOAN_APPLICATIONS', REF_ENTITY_DOMAIN => 'table'))
ORDER BY TABLE_NAME, METRIC_NAME;
